### ISSUE TITLE
error with advtrains loading server

### ISSUE THREAD

**Issue by ValkyrieStella** [orwell96/advtrains#44] opened 2017-02-14 13:53 UTC
2017-02-14 08:51:27: ERROR[Main]: ServerError: Runtime error from mod 'advtrains' in callback environment_Step(): ...t_game/mods/advtrains/advtrains/advtrains/trainlogic.lua:496: attempt to perform arithmetic on field 'end_index' (a nil value)
2017-02-14 08:51:27: ERROR[Main]: stack traceback:
2017-02-14 08:51:27: ERROR[Main]: 	...t_game/mods/advtrains/advtrains/advtrains/trainlogic.lua:496: in function 'train_step_b'
2017-02-14 08:51:27: ERROR[Main]: 	...t_game/mods/advtrains/advtrains/advtrains/trainlogic.lua:78: in function <...t_game/mods/advtrains/advtrains/advtrains/trainlogic.lua:42>
2017-02-14 08:51:27: ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:412: in function </usr/share/minetest/builtin/game/register.lua:392>
^C
[root@localhost ~]#

**Comment by orwell96** [comment] 2017-02-15 07:56
This is a duplicate of #34, after looking at the code now I know the cause
Temporary fix is as described there
Are you sure you want to run a minetestserver as root?

**Closed as completed** 2017-02-15 07:56 UTC
